name: casino_scraping
description: A sample command-line application.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  dio: ^5.4.3+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
